### ISSUE TITLE
Change url of attendee registration endpoints

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api-registration#35]
- [x] Convert `GET, PUT, POST /registration/` and `GET /registration/{id}/` to `GET, PUT, POST /registration/attendee/` and `GET /registration/attendee/{id}/`
- [x] Add a new `GET /registration/{id}/` which returns all the registrations (mentor, attendee) for a given user's id
- [x] Add a new `GET /registration/` which returns all the registrations (mentor, attendee) for the current user

Since this change breaks the service's interface, it may be necessary to update other services to use new endpoints.

**Comment by PradyumnaShome** [comment]
What would be a suitable response format for the last two endpoints?

**Comment by ASankaran** [comment]
Let do:
```
{
    "attendee": <ATTENDEE_REGISTRATION_MODEL>,
    "mentor": <MENTOR_REGISTRATION_MODEL>
}
```

If a user does not have a registration in one of those categories the field should be `null`.
